### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by NakiriRuri** [journey-ad/sd-webui-bilingual-localization#1]
能否把没有对应汉化的选项的字体同样调成双语对照一样的大小？这样即使汉化更新不及时，也不会看着不协调。

**Comment by NakiriRuri** [comment]
![图片](https://user-images.githubusercontent.com/75141113/221525916-f2082354-eaf4-4331-a037-9ca81f10040a.png)
同时发现这里的中文是居中的，但是英文是对齐中文的，看着有点奇怪。

**Comment by NakiriRuri** [comment]
同时发现，其他操作里面的三个选项，不是完全居中的，能调节一下吗？

**Comment by journey-ad** [comment]
已在 #4 中调整
