### ISSUE TITLE
请问全界面汉化在哪里下载啊

### ISSUE THREAD

**Issue by tcflying** [journey-ad/sd-webui-bilingual-localization#14]

**Comment by journey-ad** [comment]
可以安装其他语言包扩展，或者使用我整理的语言包文件，下载 json 文件，放到`localization`下就行
https://gist.github.com/journey-ad/d98ed173321658be6e51f752d6e6163c

最近几周我暂时没有精力跟进，所以新插件或者新功能的翻译支持会不完整   
除此外如果有功能上的问题欢迎随时报告，我会抽时间优先处理

**Comment by journey-ad** [comment]
issue超时关闭，有问题请重新打开
