### ISSUE TITLE
显示不出来汉化

### ISSUE THREAD

**Issue by yjw199596** [journey-ad/sd-webui-bilingual-localization#16]
![image](https://user-images.githubusercontent.com/59904710/227512668-cc89a98c-8e2b-4d5d-a694-17a8320a7425.png)
webUI也重启了，也刷新了，不显示汉化的东西呢

**Comment by journey-ad** [comment]
参考[这个issue](https://github.com/journey-ad/sd-webui-bilingual-localization/issues/14#issuecomment-1478849700)
