### ISSUE TITLE
/* 浏览器125% 字样重叠 自定义调整 */

### ISSUE THREAD

**Issue by cellifeer** [journey-ad/sd-webui-bilingual-localization#17]
const customCSS = `
    .bilingual__trans_wrapper {
      display: inline-flex;
      flex-direction: column;
      align-items: center;
      font-size: 9px; /* 浏览器125% 字样重叠 自定义调整 */
      line-height: 0.9; /* 浏览器125% 字样重叠 自定义调整 */
    }
    
    .bilingual__trans_wrapper em {
      font-style: normal;
    }

    fieldset span.text-gray-500:has(.bilingual__trans_wrapper),
    .gr-block.gr-box span.text-gray-500:has(.bilingual__trans_wrapper),
    label.block span:has(.bilingual__trans_wrapper) {
      top: -1.2em; /* 浏览器125% 字样重叠 自定义调整 */
      line-height:0.9; /* 浏览器125% 字样重叠 自定义调整 */
    }

    #txtimg_hr_finalres .bilingual__trans_wrapper em,
    #tab_ti .output-html .bilingual__trans_wrapper em,
    #dynamic-prompting .output-html .bilingual__trans_wrapper em,
    #txt2img_script_container .output-html .bilingual__trans_wrapper em,
    #available_extensions .extension-tag .bilingual__trans_wrapper em {
      display: none;
    }
    
    #settings .bilingual__trans_wrapper:not(#settings .tabitem .bilingual__trans_wrapper),
    label>span>.bilingual__trans_wrapper,
    .w-full>span>.bilingual__trans_wrapper,
    .output-html .bilingual__trans_wrapper:not(th .bilingual__trans_wrapper),
    .output-markdown .bilingual__trans_wrapper,
    .posex_setting_cont .bilingual__trans_wrapper:not(.posex_bg .bilingual__trans_wrapper) /* Posex extension */
    {
      font-size: 9px; /* 浏览器125% 字样重叠 自定义调整 */
      align-items: flex-start;
    }

    #extensions label .bilingual__trans_wrapper,
    #available_extensions td .bilingual__trans_wrapper {
      font-size: inherit;
      line-height: inherit;
    }
    
    textarea::placeholder {
      line-height: 0.9; /* 浏览器125% 字样重叠 自定义调整 */
      padding: 3px 0; /* 浏览器125% 字样重叠 自定义调整 */
    }
    
    label>span {
      line-height: 0.9; /* 浏览器125% 字样重叠 自定义调整 */
    }
    
    div[data-testid="image"]>div>div.touch-none>div {
      background-color: rgba(255, 255, 255, .6);
      color: #222;
    }
    
    /* Posex extension */
    .posex_bg {
      white-space: nowrap;
    }
    `

**Comment by journey-ad** [comment]
插件对webui样式做了一些调整以适应双语显示，如果不习惯调整后的样式可以在`user.css`中覆盖
