### ISSUE TITLE
webui 三月20日后的Gradio更新使本插件的功能失效

### ISSUE THREAD

**Issue by NakiriRuri** [journey-ad/sd-webui-bilingual-localization#18]

**Comment by Jeason0228** [comment]
昨天用的好好的,今天就只剩英文了 
python: 3.10.7  •  torch: 1.12.1+cpu  •  xformers: 0.0.17.dev464  •  gradio: 3.16.2  •  commit: [a9fed7c3]

**Comment by journey-ad** [comment]
https://github.com/journey-ad/sd-webui-bilingual-localization/commit/ec7c08b2a62a08659ebca5dd4fd529794fb17857

插件已经对gradio 3.23.0做了兼容，可以更新看看   
建议禁用其他插件后测试，因为有部分插件未适配新版本gradio，会导致整个ui界面报错异常

**Comment by bjl101501** [comment]
> [ec7c08b](https://github.com/journey-ad/sd-webui-bilingual-localization/commit/ec7c08b2a62a08659ebca5dd4fd529794fb17857)
> 
> 插件已经对gradio 3.23.0做了兼容，可以更新看看 建议禁用其他插件后测试，因为有部分插件未适配新版本gradio，会导致整个ui界面报错异常

还是不行哎，没有报错，就是不生效

**Comment by NakiriRuri** [comment]
问题已修复，感谢作者辛勤工作！
