### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by HLSS-Hen** [journey-ad/sd-webui-bilingual-localization#19]
扩展启用后显示此错误，然后整个页面功能崩溃。

使用的 https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN

**Comment by journey-ad** [comment]
更新到插件最新版本，禁用其他插件进行测试，仍有问题的话截图报错详情看看

**Comment by journey-ad** [comment]
issue超时关闭，有问题请重新打开
