### ISSUE TITLE
双语翻译插件在SD新版本无法正常使用

### ISSUE THREAD

**Issue by ggwazh** [journey-ad/sd-webui-bilingual-localization#20]
1、首先是与openpose-editor插件有冲突，安装openpose-editor插件后双语翻译插件就失效。
2、即使关闭openpose-editor插件后双语插件可以运行，也会出现其它的bug,比如在Additional Networks里无法选择lora模型，ControlNet里也无法选择预处理模型。
暂时就发现这些问题，因为基本无法使用，所以暂时关闭了双语插件，希望作者能改进一下这些BUG，非常喜欢这个双语插件，希望能尽快再用上，谢谢

**Comment by journey-ad** [comment]
openpose-editor覆盖了一个常用的api，会导致webui内置的图片查看器和其他扩展报错，我已经给开发者提了issue https://github.com/fkunn1326/openpose-editor/issues/96

双语插件对此做了兼容处理，同时下拉框无法选择的问题在新版本中应该已经修复了

**Comment by ggwazh** [comment]
今早我将openpose-editor插件关闭，升级了一下SD和其它插件，现在双语插件已经可以正常使用，真的是太棒了，作者处理问题的速度太快了，非常感谢！
