### ISSUE TITLE
不支持Scan Models for Civitai的内容翻译。

### ISSUE THREAD

**Issue by meishild** [journey-ad/sd-webui-bilingual-localization#21]
已经在翻译文件内做了映射还是无法进行翻译。
![截图](https://user-images.githubusercontent.com/3060761/228448111-ed98da41-2446-4cdd-940c-b9adeb518b90.jpg)

同时能否增加修改字体，我想要针对这套webui页面进行字体的修改。

**Comment by journey-ad** [comment]
无法翻译的问题我周末看下

自定义样式可以通过调整`user.css`实现，也有一些插件可以实现自定义样式

**Comment by journey-ad** [comment]
Fixed in https://github.com/journey-ad/sd-webui-bilingual-localization/commit/e664064b07f61499e7cbc6f4f3616d0a9b6f3c99

**Comment by meishild** [comment]
已经可以了，感谢
