### ISSUE TITLE
与Stable-Diffusion-Webui-Civitai-Helper插件有冲突

### ISSUE THREAD

**Issue by ggwazh** [journey-ad/sd-webui-bilingual-localization#22]
安装Stable-Diffusion-Webui-Civitai-Helper插件，同时开启双语插件后，在显示模型介面的Checkpoints和lora方框图显示页，无法显示Stable-Diffusion-Webui-Civitai-Helper插件的四个快捷小图标，有人在Stable-Diffusion-Webui-Civitai-Helper作者页面反映了这个问题，作者说是双语翻译插件修改了js或内嵌html脚本（本人小白，不太懂这是什么意思），见Stable-Diffusion-Webui-Civitai-Helper相关问题页的这个提问——“[BUG] Missing Icons #77”，两个插件都是非常好的插件，希望能够互相兼容，烦请作者能解决一下，谢谢

**Comment by journey-ad** [comment]
更新Civitai-Helper和双语插件到最新版本后试下，现在应该已经兼容了

**Comment by ggwazh** [comment]
刚才升级后试了一下，确实已经好了，真的是太棒了，谢谢
