### ISSUE TITLE
单独下载的语言文件不知道要放在哪里才能在下拉菜单中显示？

### ISSUE THREAD

**Issue by Amber-Xxx** [journey-ad/sd-webui-bilingual-localization#23]
抱歉完全小白，下载了“I18N_sd-webui-zh_CN.json”，但是这个放在“sd-webui-bilingual-localization”里面所有的位置都试过了，但是还是无法在下拉菜单里显示。请问到底下载语言包之后要怎么用呢？
谢谢！

**Comment by justsonghua** [comment]
\stable-diffusion-webui\localizations

试试这个路径

**Comment by journey-ad** [comment]
单个语言包 JSON 可以放到 webui 根目录下的 `localizations` 目录   
或者也可以安装第三方语言包扩展
