### ISSUE TITLE
[Bug] 下拉菜单显示 __biligual__will_be_raplaced__

### ISSUE THREAD

**Issue by justsonghua** [journey-ad/sd-webui-bilingual-localization#24]
通过下拉菜单选择Checkpoints, VAE, Sampling method 和 Upscaler后，下拉菜单显示**__biligual__will_be_raplaced__**。

如果通过Extra Networks选择Checkpoint则不会出现该问题。

<img width="645" alt="228779375-694295a3-47c7-4a4b-9a26-1bd72262dfd4" src="https://user-images.githubusercontent.com/41994375/229075215-5c1d90d5-b969-4370-830d-82f181b03575.png">

<img width="388" alt="228781513-5ff3700b-996f-476b-8e95-d34ef4f6e472" src="https://user-images.githubusercontent.com/41994375/229075217-6b0974e2-11af-4208-84c9-2e3f897df818.png">

<img width="259" alt="228779354-2e648f2a-178b-4511-98ed-d6154f31935d" src="https://user-images.githubusercontent.com/41994375/229075227-38ad7102-74d2-4f4b-adb2-af66cd5e215d.png">

通常来说，所选择Checkpoints, VAE, Sampling method 和 Upscaler的名称应该显示在下拉菜单框中（当下拉菜单收起时）。

webui版本：
**22bcc7b**（https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81）
可能在更早的一两个版本就出现了，但是前两天webui的更新频率特别高，所以不能确定是从具体哪个版本开始的。

操作环境：
Win11 22H2 22621.1413
Chrome Microsoft Edge

webui-user.bat指令：
```
@echo off

git pull

set CUDA_VISIBLE_DEVICES=0

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --no-half-vae

call webui.bat
```

控制台日志：

```
Loading VAE weights specified in settings: D:\Program Files (xStu)\A.I.Drawing\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying xformers cross attention optimization.
VAE weights loaded.
Loading weights [1d1e459f9f] from D:\Program Files (xStu)\A.I.Drawing\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5.safetensors
Loading VAE weights specified in settings: cached vae-ft-mse-840000-ema-pruned.safetensors
Applying xformers cross attention optimization.
Weights loaded in 6.1s (load weights from disk: 0.6s, apply weights to model: 4.8s, load VAE: 0.1s, move model to device: 0.5s).

Total progress: 0it [00:00, ?it/s]
```

拓展列表：

<img width="945" alt="228781900-9b8ecece-5992-4b54-b513-b6c1e3ce5250" src="https://user-images.githubusercontent.com/41994375/229076313-2ad11666-acaa-4092-ba8a-88c90ce19fc3.png">

我是一个一个排查过来的，所以基本可以确定是sd-webui-bilingual-localization出现了问题，而且下拉菜单出错时显示的也是：__biligual__will_be_raplaced__。

**Comment by journey-ad** [comment]
更新双语插件后看下，之前版本是有这个问题，目前最新版 `ba2cd3f5 (Wed Mar 29 17:20:22 2023)` 应该已经修复了

**Comment by justsonghua** [comment]
还是不行，我把本地的文件夹删了，直接git最新的版本，但是这个问题还是出现了。

**Comment by gustavmilo** [comment]
在版本之间切换了几次  问题依旧 现在用的版本ID是 955df77
