### ISSUE TITLE
界面有被遮挡住，请问该如何解决（如图）

### ISSUE THREAD

**Issue by stephen-weilai** [journey-ad/sd-webui-bilingual-localization#26]
如图
![界面有被遮挡住，请问该如何解决](https://user-images.githubusercontent.com/28383641/230709530-3b324141-67ca-497a-a9c1-1229e80fa51c.jpg)

**Comment by journey-ad** [comment]
可以考虑升级webui版本，新版本webui使用的gradio 3.23不会出现这类遮挡问题

如果不能升级，可以自行在webui根目录下的`user.css`文件中添加自定义样式来增大元素间的边距和标签偏移位置等

**Comment by stephen-weilai** [comment]
好的谢谢
