### ISSUE TITLE
i couldn't change the language while i followed the tutorial, is anyone can help?

### ISSUE THREAD

**Issue by Lawrenceeeeeeeeee** [journey-ad/sd-webui-bilingual-localization#27]
hello, sir, i'm sorry to bother you, but i met a problem and couldn't to solve it.i downloaded this extension and follow the tutorial, but i still can't transform the language.here are two photos, is someone could help?

![image](https://user-images.githubusercontent.com/76642508/231056471-58ebf9b4-f76a-44fd-a6eb-486ff36f2396.png)

![image](https://user-images.githubusercontent.com/76642508/231056746-a141db45-9910-417f-b5b4-fae1eb7533fe.png)

**Comment by journey-ad** [comment]
双语插件不附带语言包，你需要自己装一个第三方语言包扩展，然后就可以在下拉框里看到了   
或者手动下载语言包JSON文件，放到 webui 根目录下的 `localizations` 目录

中文语言包可以使用我整理的版本 https://gist.github.com/journey-ad/d98ed173321658be6e51f752d6e6163c

**Comment by Lawrenceeeeeeeeee** [comment]
> 双语插件不附带语言包，你需要自己装一个第三方语言包扩展，然后就可以在下拉框里看到了 或者手动下载语言包JSON文件，放到 webui 根目录下的 `localizations` 目录
> 
> 中文语言包可以使用我整理的版本 https://gist.github.com/journey-ad/d98ed173321658be6e51f752d6e6163c

谢谢！
