### ISSUE TITLE
能否支持一下automatic，Automaitc1111已经1个月没有更新过了。

### ISSUE THREAD

**Issue by meishild** [journey-ad/sd-webui-bilingual-localization#28]
貌似automatic取消了对多语言的支持，可能插件需要改动才能运行

**Comment by journey-ad** [comment]
在 https://github.com/journey-ad/sd-webui-bilingual-localization/commit/89a02280507627dc40b5d7562691d1f03208f152 中做了支持，可以测试看看，使用方法和之前一样

**Comment by meishild** [comment]
已经试过了，确实可以了，能否把这个和1111的集成在一起？这样master版本直接就可以用，不用手动切commit了。

**Comment by journey-ad** [comment]
这个commit在主分支的，不需要单独切过去，插件之后的更新两者架构相差不大的话应该都能同时兼容

**Comment by lazzman** [comment]
automatic 打开了更新启动参数后(`--upgrade`)是不是会自动删除localizations目录啊？ 有时打开automatic就会报错localizations不存在，发现目录没了

**Comment by lazzman** [comment]
> 这个commit在主分支的，不需要单独切过去，插件之后的更新两者架构相差不大的话应该都能同时兼容

automatic 打开了更新启动参数后--upgrade是不是会自动删除localizations目录啊？ 有时打开automatic就会报错localizations不存在，发现目录没了

**Comment by Nuullll** [comment]
> > 这个commit在主分支的，不需要单独切过去，插件之后的更新两者架构相差不大的话应该都能同时兼容
> 
> automatic 打开了更新启动参数后--upgrade是不是会自动删除localizations目录啊？ 有时打开automatic就会报错localizations不存在，发现目录没了

是的。提了个PR: https://github.com/vladmandic/automatic/pull/1783
