### ISSUE TITLE
找不到简体中文语言包(zh_CN)

### ISSUE THREAD

**Issue by 13822902389** [journey-ad/sd-webui-bilingual-localization#29]
在【settings】里显示有下载，☑️并且重启，到了【User interface】界面，【Localization (requires restart)】找不到【zh_CN】,刷新很多次都没有用，同样的【Bilingual Localization】界面已经☑️【Enable Bilingual Localization】，也刷新不出来内容，全都是none。
请问我该如何解决这个问题？

**Comment by Gslullaby** [comment]
Me too

**Comment by 13822902389** [comment]
我已经找到原因了，需要找一个文件例如【zh_CN.json】，放置在【localizations】文件夹下。

**Comment by Gslullaby** [comment]
> 我已经找到原因了，需要找一个文件例如【zh_CN.json】，放置在【localizations】文件夹下。

👍

**Comment by zfhstudy** [comment]
> 

麻烦共享一下 zh_CN.json 文件

**Comment by Kevinguanwei** [comment]
请问具体怎么解决的？麻烦介绍详细点可以吗？。。。本人小白
