### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'localizations'

### ISSUE THREAD

**Issue by kyholdings** [journey-ad/sd-webui-bilingual-localization#37]
automatic: Install from URL出现如下错误，请教如何处理·，谢谢！

dirname:  localizations
2023-07-06-19:28:10 image_browser.py: Module load: E:\AI\automatic\extensions\sd-webui-bilingual-localization\scripts\bilingual_localization_helper.py: FileNotFoundError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\AI\automatic\modules\script_loading.py:13 in load_module                                                          │
│                                                                                                                      │
│   12 │   try:                                                                                                        │
│ ❱ 13 │   │   module_spec.loader.exec_module(module)                                                                  │
│   14 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 1 frames hidden ...                                                │
│                                                                                                                      │
│ E:\AI\automatic\extensions\sd-webui-bilingual-localization\scripts\bilingual_localization_helper.py:33 in <module>   │
│                                                                                                                      │
│   32                                                                                                                 │
│ ❱ 33 list_localizations(localizations_dir)                                                                           │
│   34                                                                                                                 │
│                                                                                                                      │
│ E:\AI\automatic\extensions\sd-webui-bilingual-localization\scripts\bilingual_localization_helper.py:18 in            │
│ list_localizations                                                                                                   │
│                                                                                                                      │
│   17 │                                                                                                               │
│ ❱ 18 │   for file in os.listdir(dirname):                                                                            │
│   19 │   │   fn, ext = os.path.splitext(file)                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'localizations'

**Comment by journey-ad** [comment]
在根目录新建一个文件夹`localizations `，然后把语言json文件丢进去

**Comment by kyholdings** [comment]
是这两个文件吗？ProjectSettings 和VSWorkspaceState
我已经放进去了在setting那里也可以选择了，但是我怎么都找不到这个地方：
Make sure Settings - User interface - Localization is set to None
automatic的User interface界面没有Localization的选项。去哪个文件里面可以设置？

**Comment by journey-ad** [comment]
语言包可以到https://gist.github.com/journey-ad/d98ed173321658be6e51f752d6e6163c下载，或者装一个本地化扩展

这里的提示是给使用auto111的原版sd-webui看的，automatic砍掉了本地化功能所以不用管

**Comment by kyholdings** [comment]
谢谢journey-ad
我试了各种办法，都只会显示英文菜单。算了，我还是回到A1111版本来运行了。
无论如何都谢谢你。
A1111版本安装没有问题。
