### ISSUE TITLE
有问题可以直接找我，贴吧上挂人是什么意思？

### ISSUE THREAD

**Issue by ToumanLin** [journey-ad/sd-webui-bilingual-localization#45]
楼主还把我拉黑了，导致回复都不行。是不是有点太没有礼貌了😥

从来没和发帖的这位吵过，为什么要做出这种行为？当看到非常过激的回应的时候，我在第一时间道歉的。
有任何问题，可以直接联系我。为什么要用这种行为来侮辱人？

**Comment by ToumanLin** [comment]
太过分了，这样的人身攻击，这样的行为。

**Comment by ToumanLin** [comment]
我从来就没有存在“伸手”的意愿，我本人英语相当不错完全可以看原版
用了汉化之后出现很多报错我想着自己解决，如果有源码会方便很多，这样可以直接pull request然后你们merge更方便。

我不知道为什么要这么对待我，用这么恶毒的语言

**Comment by ToumanLin** [comment]
这样恶毒的“批斗”是不是有点过分了？
说的有些话，简直太难听了。这样的语言

**Comment by journey-ad** [comment]
你是不是找错地方了，这里只是这个双语插件的源代码仓库，和任何汉化包/教程/整合包都无关，我也不认识和你吵起来的人，更不清楚前因后果，你应该去和你发生争吵的用户或平台留言或者发帖
