### ISSUE TITLE
Support sd-webui-lobe-theme / 支持sd-webui-lobe-theme

### ISSUE THREAD

**Issue by leohu1** [journey-ad/sd-webui-bilingual-localization#48]
Wish this extension could support [sd-webui-lobe-theme](https://github.com/lobehub/sd-webui-lobe-theme?tab=readme-ov-file)

希望这个拓展可以支持 [sd-webui-lobe-theme](https://github.com/lobehub/sd-webui-lobe-theme?tab=readme-ov-file)

It didn't seem to work.

目前好像不工作

![图片](https://github.com/journey-ad/sd-webui-bilingual-localization/assets/47905372/1cb81d36-bc41-4df4-b7df-15fc06933543)
![图片](https://github.com/journey-ad/sd-webui-bilingual-localization/assets/47905372/b9c61581-3fa2-4493-a5ea-2ffb44fea8ff)

**Comment by journey-ad** [comment]
测试可用，检查是否有其他插件冲突，控制台有无报错

![Snipaste_2024-02-20_17-22-36](https://github.com/journey-ad/sd-webui-bilingual-localization/assets/16256221/28dcfb1b-62e6-4309-9667-0635bbf1df9e)

**Comment by leohu1** [comment]
应该是我的问题，现在可以了
